import { Geist, Geist_Mono, Anek_Devanagari } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
import Providers from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const devanagari = Anek_Devanagari({
  variable: "--font-anek-devanagari",
  weight: ["400", "700"], // Ensure these weights are supported
  display: "swap",
  fallback: ["system-ui", "sans-serif"], // Fallback fonts
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Anek+Devanagari:wght@400;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased" style={{ fontFamily: "'Anek Devanagari', sans-serif" }}>
          <Navbar />
          {children}
      </body>
    </html>
  );
}
